name: dvote
description: Decentralized, end-to-end verifiable governance platform client library for Dart.
version: 0.18.0
homepage: https://github.com/vocdoni/dvote-dart
repository: https://github.com/vocdoni/dvote-dart.git
documentation: https://docs.vocdoni.io

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^0.12.2
  hex: ^0.1.2
  web3dart: ^2.0.0-dev.7
  convert: ^2.1.1
  protobuf: ^1.0.1
  bip39: ^1.0.3
  bip32: ^1.0.5
  crypto: ^2.1.5
  pinenacl: ^0.1.2

dev_dependencies:
  test: ^1.9.0
  # mockito: ^4.0.0
  # coverage: ^0.13.3