name: dvote
description: Decentralized, end-to-end verifiable governance platform client library for Dart.
version: 0.14.0
homepage: https://gitlab.com/vocdoni/dvote-flutter
repository: https://gitlab.com/vocdoni/dvote-flutter.git
documentation: https://vocdoni.io/docs

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  hex: ^0.1.2
  web3dart: ^2.0.0-dev.2
  convert: ^2.1.1
  protobuf: ^1.0.1
  bip39: ^1.0.3
  bip32: ^1.0.5
  crypto: ^2.1.3
  pinenacl: ^0.1.2
  dvote_native: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
